#!/usr/bin/python
import sys
import time
import select
import os

sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
while True:
	line = sys.stdin.readline()
	(v, usec) = [int(s) for s in line.split()]
	
	t1 = time.time()
	print "%d %d %d" % (v, int(t1), (t1 - int(t1)) * 1000000)
	if usec > 0:
		if usec > 500000:
			ready_to_read, ready_to_write, in_error = select.select([sys.stdin], [], [], usec / 1000000.0)
			if len(ready_to_read) > 0:
				continue
		else:
			time.sleep(usec / 1000000.0)
		t2 = time.time()
		print "%d %d %d" % (0, int(t2), (t2 - int(t2)) * 1000000)
